### PR TITLE
Play playlist and clear queue

### PR DESCRIPTION
**Pull request by ur1katz**
Added 2 options:
* Clear all videos in queue
* Play a playlist

### CODE REVIEW

**Comment by theychx** [comment]
Everything appears to work!

I've pushed some commits to my [PR](https://github.com/skorokithakis/catt/pull/127), in order to test this.

Just so we're on the same page; I've modified the yt controller in ```PyChromecast 2.3.0``` in the following way, to be able to test:
```
37c37
<     def play_video(self, video_id):
---
>     def play_video(self, video_id, list_id=None):
43c43
<         self._session.play_video(video_id)
---
>         self._session.play_video(video_id, list_id=list_id)
51a52,55
> 
>     def clear_playlist(self):
>         self.start_session_if_none()
>         self._session.clear_playlist()
```

**Comment by ur1katz** [comment]
@theychx The code looks good. 
Are you taking it directly from pychromecast or changing it only in catt?

**Comment by theychx** [comment]
I monkey-patched pychromecast in the virtual environment. :monkey_face:

**Comment by theychx** [comment]
Looking forward, I of course want to take it directly from pychromecast.

**Comment by ur1katz** [comment]
OK, so there are a few things left before opening a PR to pychromecast.

- [x] Bump the version to 0.2.0 (in this PR)
- [x] merge PR 
- [x] Update the code in pip
- [x] Verify that everything is working and updated in the pip package

I will have some time to do that tomorrow/Friday morning :)

**Comment by theychx** [comment]
```casttube 0.2.0``` is working ok.

**Comment by theychx** [comment]
@ur1katz Is everything ready for the pychromecast PR?

**Comment by theychx** [comment]
@ur1katz Is there some kind of misunderstanding here, with regards to who is going to do the ```pychromecast``` PR? I wouldn't mind doing it, only it'd be a bit awkward, as I have little concept of what goes on under the hood in ```casttube```.

**Comment by ur1katz** [comment]
@theychx  sorry about that.. i thought you were going to do the PR. 
I opened the PR to pychromecast,

**Pull request merged**
